### PR TITLE
1 prototype

### PR DESCRIPTION
**Pull request by LucasAnderson1984**
Prepare an empty project for development, cleaned up some of Joe's left over :hankey:

### CODE REVIEW

**Comment by LucasAnderson1984** [comment]
@josephbridgwaterrowe please review.

**Comment by josephbridgwaterrowe** [comment]
@LucasAnderson1984 Looks good to me, rebase time.

**Comment by josephbridgwaterrowe** [comment]
@LucasAnderson1984 no travis here, do you want to set it up together?

**Comment by LucasAnderson1984** [comment]
Yes

**Comment by josephbridgwaterrowe** [comment]
@LucasAnderson1984 let me know when.

**Comment by LucasAnderson1984** [comment]
Ready

**Comment by LucasAnderson1984** [comment]
Looks like the travis checks failed.  I believe I got the rebase correct.  Let me know.

**Comment by josephbridgwaterrowe** [comment]
@LucasAnderson1984 I'll check the Travis config in the morning and let you know what I find... I'll also make sure you have access to the site.

You may also want to amend the commit author to be yourself, rather than me.

**Comment by josephbridgwaterrowe** [comment]
@LucasAnderson1984 add the following lines to the end of the `.travis.yml` file.

```
before_script:
- cp config/database.example.yml config/database.yml
```

**Comment by josephbridgwaterrowe** [comment]
@LucasAnderson1984 you should be able to view the travis build status by clicking on the Details link beside the failed build on either of the following lines:

```
continuous-integration/travis-ci/pr
continuous-integration/travis-ci/push
```

**Comment by LucasAnderson1984** [comment]
It looks like the it keep failing due to the database.example.yml failing without adding a user or pass word.  I thought you shouldn't add it?

**Comment by josephbridgwaterrowe** [comment]
See this for instructions on setting up MySQL and Travis.

https://docs.travis-ci.com/user/database-setup/#MySQL

Also, there is no db schema because db:migrate has not been run yet.

screen shot 2015-12-31 at 9 57 39 am

**Comment by LucasAnderson1984** [comment]
Should I tag slack like you did in cantina?

**Comment by josephbridgwaterrowe** [comment]
Sure, why not.

**Comment by josephbridgwaterrowe** [comment]
I think you'll find creating `cycle_count` in travis is also unnecessary since its only using the test environment.

**Comment by LucasAnderson1984** [comment]
Changed what I was doing and added the below in travis:
- export SECRET_KEY_BASE="$(bundle exec rake secret)"
- cp config/application.example.yml config/application.yml

**Comment by LucasAnderson1984** [comment]
I'm going to rebase now that that's done with.

**Comment by josephbridgwaterrowe** [comment]
@LucasAnderson1984 cool, its looking good!

**Comment by josephbridgwaterrowe** [comment]
@LucasAnderson1984 I'm going to grab some lunch, will merge when I return if thats OK?

**Comment by LucasAnderson1984** [comment]
Yes.  Thank you for the help.

**Pull request merged**
